[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "picobot"
version = "0.1.1"
description = "A tiny bot built for simplicity"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
   "click",
   "langchain",
   "langchain-community",
   "langchain-openai",
   "langgraph",
   "rich",
]

[project.scripts]
picobot = "picobot.cli:chat"

[tool.setuptools.packages.find]
where = ["src"]
